theme: jekyll-theme-cayman
title: Kode Konveyor
description: The conveyor belt for software development
google_analytics: UA-151042094-1
repository: kode-konveyor/taskmarket-frontend

exclude:
        - tools
        - Gemfile
